# 配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.115.114.18:3306/classes?serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowMultiQueries=true
    username: classes
    password: 'cmjLSZRhp54iahfX'
  redis:
    host: 127.0.0.1
    port: 6379
  jackson:
    #json转换的时间格式设置
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      indent_output: true



mybatis:
  #配置别名基础包
  mapper-locations: classpath:mybatis/*Mapper.xml,classpath*:/mappers/*.xml
  type-aliases-package: com.springboot.management.vo
  configuration:
    #下划线命名与驼峰命名法的自动映射
    map-underscore-to-camel-case: true
server:
  port: 8080
  servlet:
    context-path:
#设置指定包的日志输出级别
logging:
  level:
    com: debug
jwt:
  #请求header所携带token的属性名
  header: Authorization
  #用户自定义的口令
  secret: mySecret
  #失效时间
  expiration: 604800
  #承载字符串
  tokenHead: Bearer
  route:
    authentication:
      #token授权url
      path: /auth
      #刷新token的url
      refresh: /refresh

absoluteImgPath: F://localimg/
sonImgPath: /images/

itcast-fastdfs:
  #文件上传临时目录
  upload_location: D:\\



